export const MIN_DESCRIPTION_LENGTH = 0;
export const MAX_DESCRIPTION_LENGTH = 150;

export const MIN_BRIEF_DESCRIPTION_LENGTH = 0;
export const MAX_BRIEF_DESCRIPTION_LENGTH = 50;

export const MIN_COMMENT_LENGTH = 0;
export const MAX_COMMENT_LENGTH = 150;

export const MIN_SELF_INTRODUCTION_LENGTH = 0;
export const MAX_SELF_INTRODUCTION_LENGTH = 100;
